# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

MIRYOKU_KLUDGE_THUMBCOMBOS=yes
MIRYOKU_CUSTOM_COMBO_COUNT=1

MIRYOKU_LAYERS=FLIP_SYM,FLIP_MEDIA
MIRYOKU_THUMBKEYS_LAYER=LO=MOUSE,LM=SYM,LI=NAV,RI=FUN,RO=MEDIA
MIRYOKU_THUMBKEYS_KEYCODE=LO=KC_TAB,LM=KC_ESC,LI=KC_ENT,RI=KC_BSPC,RM=KC_SPC
